// Subcategorías por categoría — chips para filtrar productos dentro del mundo.
// Cada subcategoría se mapea a un patrón de búsqueda en el título del producto.

export type Subcategory = { id: string; name: string; emoji: string; match: (title: string) => boolean };

const has = (...keys: string[]) => (t: string) => {
  const s = t.toLowerCase();
  return keys.some((k) => s.includes(k.toLowerCase()));
};

export const SUBCATEGORIES: Record<string, Subcategory[]> = {
  tech: [
    { id: "fundas", name: "Fundas", emoji: "📱", match: has("funda") },
    { id: "auriculares", name: "Auriculares", emoji: "🎧", match: has("auricular") },
    { id: "smartwatch", name: "Smartwatch", emoji: "⌚", match: has("smartwatch") },
    { id: "parlantes", name: "Parlantes", emoji: "🔊", match: has("parlante") },
    { id: "camaras", name: "Cámaras", emoji: "📷", match: has("cámara", "camara") },
    { id: "robot-ia", name: "Mini robot IA", emoji: "🤖", match: has("robot ia", "mini robot") },
    { id: "monitores", name: "Monitores", emoji: "🖥️", match: has("monitor") },
    { id: "gamer", name: "Gamer", emoji: "🎮", match: has("gamer", "setup gamer") },
    { id: "drones", name: "Drones", emoji: "🛸", match: has("drone", "helicópter") },
    { id: "smart-glasses", name: "Smart Glasses", emoji: "🕶️", match: has("smart glasses") },
    { id: "microfonos", name: "Micrófonos", emoji: "🎙️", match: has("micrófono", "microfono") },
    { id: "proyectores", name: "Proyectores", emoji: "📽️", match: has("proyector") },
    { id: "cargadores", name: "Cargadores", emoji: "🔌", match: has("cargador") },
    { id: "luces-led", name: "Luces LED", emoji: "💡", match: has("led") },
    { id: "soportes", name: "Soportes celular", emoji: "📲", match: has("soporte celular", "soporte") },
  ],
  electronica: [
    { id: "cafeteras", name: "Cafeteras", emoji: "☕", match: has("cafeter") },
    { id: "freidoras", name: "Freidoras de aire", emoji: "🍳", match: has("freidora") },
    { id: "licuadoras", name: "Licuadoras", emoji: "🥤", match: has("licuadora") },
    { id: "batidoras", name: "Batidoras", emoji: "🍰", match: has("batidora") },
    { id: "exprimidores", name: "Exprimidores", emoji: "🍊", match: has("exprimidor") },
    { id: "waffleras", name: "Waffleras", emoji: "🧇", match: has("wafflera") },
    { id: "pochocleras", name: "Pochocleras", emoji: "🍿", match: has("pochoclera") },
    { id: "espumadores", name: "Espumadores", emoji: "🥛", match: has("espumador") },
    { id: "robot-aspira", name: "Aspiradoras robot", emoji: "🤖", match: has("aspiradora robot") },
    { id: "aspira-mano", name: "Aspiradoras de mano", emoji: "🧹", match: has("aspiradora de mano") },
    { id: "limpia-vidrios", name: "Limpia vidrios", emoji: "🪟", match: has("limpia vidrios") },
    { id: "afeitadoras", name: "Afeitadoras", emoji: "🪒", match: has("afeitadora") },
    { id: "hielo", name: "Máquina de hielo", emoji: "🧊", match: has("hielo") },
  ],
  hogar: [
    { id: "vajillas", name: "Vajillas", emoji: "🍽️", match: has("vajilla") },
    { id: "cocina", name: "Cocina", emoji: "🥄", match: has("cocina", "utensilios") },
    { id: "decoracion", name: "Decoración", emoji: "🖼️", match: has("cuadro", "decorativ") },
    { id: "iluminacion", name: "Iluminación", emoji: "💡", match: has("lámpara", "lampara") },
    { id: "espejos", name: "Espejos", emoji: "🪞", match: has("espejo") },
    { id: "velas", name: "Velas y difusores", emoji: "🕯️", match: has("vela", "difusor") },
    { id: "canastos", name: "Canastos", emoji: "🧺", match: has("canasto") },
    { id: "toallas", name: "Toallas", emoji: "🛁", match: has("toalla") },
    { id: "organizadoras", name: "Cajas organizadoras", emoji: "📦", match: has("caja organizadora", "organizador") },
    { id: "proy-estrellas", name: "Proyector estrellas", emoji: "✨", match: has("proyector estrellas") },
    { id: "sunset", name: "Lámpara sunset", emoji: "🌅", match: has("puesta de sol", "sunset") },
  ],
  gym: [
    { id: "pesas", name: "Pesas", emoji: "🏋️", match: has("pesas", "hexagonales") },
    { id: "mancuernas", name: "Mancuernas", emoji: "💪", match: has("mancuerna") },
    { id: "barras", name: "Barras", emoji: "🏋️", match: has("barra olímpica", "barra") },
    { id: "futbol", name: "Fútbol", emoji: "⚽", match: has("fútbol", "futbol") },
    { id: "boxeo", name: "Boxeo", emoji: "🥊", match: has("boxeo", "guantes") },
    { id: "basquet", name: "Básquet", emoji: "🏀", match: has("básquet", "basquet") },
    { id: "rugby", name: "Rugby", emoji: "🏉", match: has("rugby") },
    { id: "hockey", name: "Hockey", emoji: "🏒", match: has("hockey") },
    { id: "snow", name: "Ski / Snowboard", emoji: "🏂", match: has("snowboard", "ski") },
    { id: "bandas", name: "Bandas elásticas", emoji: "💪", match: has("banda elástica", "bandas elásticas") },
    { id: "conos", name: "Conos", emoji: "🔶", match: has("cono") },
    { id: "soga", name: "Soga", emoji: "🪢", match: has("soga") },
    { id: "rueda", name: "Rueda abdominal", emoji: "⚙️", match: has("rueda abdominal") },
    { id: "toallas-gym", name: "Toallas gym", emoji: "🧖", match: has("toalla microfibra", "toalla") },
  ],
  belleza: [
    { id: "mascarillas", name: "Mascarillas", emoji: "🌸", match: has("mascarilla") },
    { id: "mascara-led", name: "Máscara LED", emoji: "💆", match: has("máscara led") },
    { id: "masajeador", name: "Masajeadores", emoji: "✨", match: has("masajeador") },
    { id: "unas", name: "Uñas", emoji: "💅", match: has("uñas", "press-on") },
    { id: "esmaltes", name: "Esmaltes", emoji: "💗", match: has("esmalte") },
    { id: "poros", name: "Limpieza de poros", emoji: "🫧", match: has("poro") },
    { id: "rejuvenecimiento", name: "Rejuvenecimiento", emoji: "🧴", match: has("rejuvene", "serum") },
    { id: "brochas", name: "Brochas", emoji: "🖌️", match: has("brocha") },
    { id: "skincare", name: "Skincare", emoji: "🌷", match: has("skincare") },
    { id: "planchita", name: "Planchita", emoji: "💇", match: has("planchita") },
    { id: "secador", name: "Secador", emoji: "💨", match: has("secador") },
    { id: "rizadora", name: "Rizadora", emoji: "💁", match: has("rizadora") },
    { id: "uv", name: "Lámpara UV", emoji: "💡", match: has("uv") },
    { id: "vinchas", name: "Vinchas", emoji: "🎀", match: has("vincha") },
    { id: "parches", name: "Parches granitos", emoji: "🩹", match: has("parche") },
    { id: "depilador", name: "Depilador", emoji: "✨", match: has("depilador") },
  ],
  joyeria: [
    { id: "anillos", name: "Anillos", emoji: "💍", match: has("anillo") },
    { id: "pulseras", name: "Pulseras", emoji: "📿", match: has("pulsera") },
    { id: "collares", name: "Collares", emoji: "🔗", match: has("collar", "cadena") },
    { id: "aros", name: "Aros", emoji: "💫", match: has("aros") },
    { id: "relojes", name: "Relojes", emoji: "⌚", match: has("reloj") },
    { id: "lentes", name: "Lentes", emoji: "🕶️", match: has("lentes") },
    { id: "dijes", name: "Dijes", emoji: "✨", match: has("dije") },
  ],
};
