/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistrarMarcaRouteImport } from './routes/registrar-marca'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPanelIndexRouteImport } from './routes/admin-panel.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as GroupSlugRouteImport } from './routes/group.$slug'
import { Route as CategoriasIdRouteImport } from './routes/categorias.$id'
import { Route as AdminMachineRouteImport } from './routes/admin.machine'
import { Route as AdminPanelTodoRouteImport } from './routes/admin-panel.todo'
import { Route as AdminPanelStockRouteImport } from './routes/admin-panel.stock'
import { Route as AdminPanelReclamosRouteImport } from './routes/admin-panel.reclamos'
import { Route as AdminPanelProductosRouteImport } from './routes/admin-panel.productos'
import { Route as AdminPanelProduccionRouteImport } from './routes/admin-panel.produccion'
import { Route as AdminPanelPersonalizadosRouteImport } from './routes/admin-panel.personalizados'
import { Route as AdminPanelPedidosRouteImport } from './routes/admin-panel.pedidos'
import { Route as AdminPanelPagosRouteImport } from './routes/admin-panel.pagos'
import { Route as AdminPanelGruposRouteImport } from './routes/admin-panel.grupos'
import { Route as AdminPanelEnviosRouteImport } from './routes/admin-panel.envios'
import { Route as AdminPanelEmpleadosRouteImport } from './routes/admin-panel.empleados'
import { Route as AdminPanelEmpaquetadoRouteImport } from './routes/admin-panel.empaquetado'
import { Route as AdminPanelConfiguracionRouteImport } from './routes/admin-panel.configuracion'
import { Route as AdminPanelClientesRouteImport } from './routes/admin-panel.clientes'
import { Route as AdminPanelCalidadRouteImport } from './routes/admin-panel.calidad'
import { Route as ProductsSlugDesignRouteImport } from './routes/products.$slug.design'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarMarcaRoute = RegistrarMarcaRouteImport.update({
  id: '/registrar-marca',
  path: '/registrar-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelIndexRoute = AdminPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSlugRoute = GroupSlugRouteImport.update({
  id: '/group/$slug',
  path: '/group/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIdRoute = CategoriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriasRoute,
} as any)
const AdminMachineRoute = AdminMachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelTodoRoute = AdminPanelTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelStockRoute = AdminPanelStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelReclamosRoute = AdminPanelReclamosRouteImport.update({
  id: '/reclamos',
  path: '/reclamos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProductosRoute = AdminPanelProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProduccionRoute = AdminPanelProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPersonalizadosRoute =
  AdminPanelPersonalizadosRouteImport.update({
    id: '/personalizados',
    path: '/personalizados',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AdminPanelPedidosRoute = AdminPanelPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPagosRoute = AdminPanelPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelGruposRoute = AdminPanelGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelEnviosRoute = AdminPanelEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelEmpleadosRoute = AdminPanelEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelEmpaquetadoRoute = AdminPanelEmpaquetadoRouteImport.update({
  id: '/empaquetado',
  path: '/empaquetado',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelConfiguracionRoute = AdminPanelConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelClientesRoute = AdminPanelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelCalidadRoute = AdminPanelCalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => AdminPanelRoute,
} as any)
const ProductsSlugDesignRoute = ProductsSlugDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ProductsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-panel/calidad': typeof AdminPanelCalidadRoute
  '/admin-panel/clientes': typeof AdminPanelClientesRoute
  '/admin-panel/configuracion': typeof AdminPanelConfiguracionRoute
  '/admin-panel/empaquetado': typeof AdminPanelEmpaquetadoRoute
  '/admin-panel/empleados': typeof AdminPanelEmpleadosRoute
  '/admin-panel/envios': typeof AdminPanelEnviosRoute
  '/admin-panel/grupos': typeof AdminPanelGruposRoute
  '/admin-panel/pagos': typeof AdminPanelPagosRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/personalizados': typeof AdminPanelPersonalizadosRoute
  '/admin-panel/produccion': typeof AdminPanelProduccionRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/admin-panel/reclamos': typeof AdminPanelReclamosRoute
  '/admin-panel/stock': typeof AdminPanelStockRoute
  '/admin-panel/todo': typeof AdminPanelTodoRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/admin-panel/': typeof AdminPanelIndexRoute
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-panel/calidad': typeof AdminPanelCalidadRoute
  '/admin-panel/clientes': typeof AdminPanelClientesRoute
  '/admin-panel/configuracion': typeof AdminPanelConfiguracionRoute
  '/admin-panel/empaquetado': typeof AdminPanelEmpaquetadoRoute
  '/admin-panel/empleados': typeof AdminPanelEmpleadosRoute
  '/admin-panel/envios': typeof AdminPanelEnviosRoute
  '/admin-panel/grupos': typeof AdminPanelGruposRoute
  '/admin-panel/pagos': typeof AdminPanelPagosRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/personalizados': typeof AdminPanelPersonalizadosRoute
  '/admin-panel/produccion': typeof AdminPanelProduccionRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/admin-panel/reclamos': typeof AdminPanelReclamosRoute
  '/admin-panel/stock': typeof AdminPanelStockRoute
  '/admin-panel/todo': typeof AdminPanelTodoRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/admin-panel': typeof AdminPanelIndexRoute
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-panel/calidad': typeof AdminPanelCalidadRoute
  '/admin-panel/clientes': typeof AdminPanelClientesRoute
  '/admin-panel/configuracion': typeof AdminPanelConfiguracionRoute
  '/admin-panel/empaquetado': typeof AdminPanelEmpaquetadoRoute
  '/admin-panel/empleados': typeof AdminPanelEmpleadosRoute
  '/admin-panel/envios': typeof AdminPanelEnviosRoute
  '/admin-panel/grupos': typeof AdminPanelGruposRoute
  '/admin-panel/pagos': typeof AdminPanelPagosRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/personalizados': typeof AdminPanelPersonalizadosRoute
  '/admin-panel/produccion': typeof AdminPanelProduccionRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/admin-panel/reclamos': typeof AdminPanelReclamosRoute
  '/admin-panel/stock': typeof AdminPanelStockRoute
  '/admin-panel/todo': typeof AdminPanelTodoRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/admin-panel/': typeof AdminPanelIndexRoute
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-panel'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin-panel/calidad'
    | '/admin-panel/clientes'
    | '/admin-panel/configuracion'
    | '/admin-panel/empaquetado'
    | '/admin-panel/empleados'
    | '/admin-panel/envios'
    | '/admin-panel/grupos'
    | '/admin-panel/pagos'
    | '/admin-panel/pedidos'
    | '/admin-panel/personalizados'
    | '/admin-panel/produccion'
    | '/admin-panel/productos'
    | '/admin-panel/reclamos'
    | '/admin-panel/stock'
    | '/admin-panel/todo'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/admin-panel/'
    | '/products/$slug/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin-panel/calidad'
    | '/admin-panel/clientes'
    | '/admin-panel/configuracion'
    | '/admin-panel/empaquetado'
    | '/admin-panel/empleados'
    | '/admin-panel/envios'
    | '/admin-panel/grupos'
    | '/admin-panel/pagos'
    | '/admin-panel/pedidos'
    | '/admin-panel/personalizados'
    | '/admin-panel/produccion'
    | '/admin-panel/productos'
    | '/admin-panel/reclamos'
    | '/admin-panel/stock'
    | '/admin-panel/todo'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/admin-panel'
    | '/products/$slug/design'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-panel'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin-panel/calidad'
    | '/admin-panel/clientes'
    | '/admin-panel/configuracion'
    | '/admin-panel/empaquetado'
    | '/admin-panel/empleados'
    | '/admin-panel/envios'
    | '/admin-panel/grupos'
    | '/admin-panel/pagos'
    | '/admin-panel/pedidos'
    | '/admin-panel/personalizados'
    | '/admin-panel/produccion'
    | '/admin-panel/productos'
    | '/admin-panel/reclamos'
    | '/admin-panel/stock'
    | '/admin-panel/todo'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/admin-panel/'
    | '/products/$slug/design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  GruposRoute: typeof GruposRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RegistrarMarcaRoute: typeof RegistrarMarcaRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GroupSlugRoute: typeof GroupSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar-marca': {
      id: '/registrar-marca'
      path: '/registrar-marca'
      fullPath: '/registrar-marca'
      preLoaderRoute: typeof RegistrarMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel/': {
      id: '/admin-panel/'
      path: '/'
      fullPath: '/admin-panel/'
      preLoaderRoute: typeof AdminPanelIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$slug': {
      id: '/group/$slug'
      path: '/group/$slug'
      fullPath: '/group/$slug'
      preLoaderRoute: typeof GroupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$id': {
      id: '/categorias/$id'
      path: '/$id'
      fullPath: '/categorias/$id'
      preLoaderRoute: typeof CategoriasIdRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/admin/machine': {
      id: '/admin/machine'
      path: '/machine'
      fullPath: '/admin/machine'
      preLoaderRoute: typeof AdminMachineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin-panel/todo': {
      id: '/admin-panel/todo'
      path: '/todo'
      fullPath: '/admin-panel/todo'
      preLoaderRoute: typeof AdminPanelTodoRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/stock': {
      id: '/admin-panel/stock'
      path: '/stock'
      fullPath: '/admin-panel/stock'
      preLoaderRoute: typeof AdminPanelStockRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/reclamos': {
      id: '/admin-panel/reclamos'
      path: '/reclamos'
      fullPath: '/admin-panel/reclamos'
      preLoaderRoute: typeof AdminPanelReclamosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/productos': {
      id: '/admin-panel/productos'
      path: '/productos'
      fullPath: '/admin-panel/productos'
      preLoaderRoute: typeof AdminPanelProductosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/produccion': {
      id: '/admin-panel/produccion'
      path: '/produccion'
      fullPath: '/admin-panel/produccion'
      preLoaderRoute: typeof AdminPanelProduccionRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/personalizados': {
      id: '/admin-panel/personalizados'
      path: '/personalizados'
      fullPath: '/admin-panel/personalizados'
      preLoaderRoute: typeof AdminPanelPersonalizadosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/pedidos': {
      id: '/admin-panel/pedidos'
      path: '/pedidos'
      fullPath: '/admin-panel/pedidos'
      preLoaderRoute: typeof AdminPanelPedidosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/pagos': {
      id: '/admin-panel/pagos'
      path: '/pagos'
      fullPath: '/admin-panel/pagos'
      preLoaderRoute: typeof AdminPanelPagosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/grupos': {
      id: '/admin-panel/grupos'
      path: '/grupos'
      fullPath: '/admin-panel/grupos'
      preLoaderRoute: typeof AdminPanelGruposRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/envios': {
      id: '/admin-panel/envios'
      path: '/envios'
      fullPath: '/admin-panel/envios'
      preLoaderRoute: typeof AdminPanelEnviosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/empleados': {
      id: '/admin-panel/empleados'
      path: '/empleados'
      fullPath: '/admin-panel/empleados'
      preLoaderRoute: typeof AdminPanelEmpleadosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/empaquetado': {
      id: '/admin-panel/empaquetado'
      path: '/empaquetado'
      fullPath: '/admin-panel/empaquetado'
      preLoaderRoute: typeof AdminPanelEmpaquetadoRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/configuracion': {
      id: '/admin-panel/configuracion'
      path: '/configuracion'
      fullPath: '/admin-panel/configuracion'
      preLoaderRoute: typeof AdminPanelConfiguracionRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/clientes': {
      id: '/admin-panel/clientes'
      path: '/clientes'
      fullPath: '/admin-panel/clientes'
      preLoaderRoute: typeof AdminPanelClientesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/calidad': {
      id: '/admin-panel/calidad'
      path: '/calidad'
      fullPath: '/admin-panel/calidad'
      preLoaderRoute: typeof AdminPanelCalidadRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/products/$slug/design': {
      id: '/products/$slug/design'
      path: '/design'
      fullPath: '/products/$slug/design'
      preLoaderRoute: typeof ProductsSlugDesignRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMachineRoute: typeof AdminMachineRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMachineRoute: AdminMachineRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdminPanelRouteChildren {
  AdminPanelCalidadRoute: typeof AdminPanelCalidadRoute
  AdminPanelClientesRoute: typeof AdminPanelClientesRoute
  AdminPanelConfiguracionRoute: typeof AdminPanelConfiguracionRoute
  AdminPanelEmpaquetadoRoute: typeof AdminPanelEmpaquetadoRoute
  AdminPanelEmpleadosRoute: typeof AdminPanelEmpleadosRoute
  AdminPanelEnviosRoute: typeof AdminPanelEnviosRoute
  AdminPanelGruposRoute: typeof AdminPanelGruposRoute
  AdminPanelPagosRoute: typeof AdminPanelPagosRoute
  AdminPanelPedidosRoute: typeof AdminPanelPedidosRoute
  AdminPanelPersonalizadosRoute: typeof AdminPanelPersonalizadosRoute
  AdminPanelProduccionRoute: typeof AdminPanelProduccionRoute
  AdminPanelProductosRoute: typeof AdminPanelProductosRoute
  AdminPanelReclamosRoute: typeof AdminPanelReclamosRoute
  AdminPanelStockRoute: typeof AdminPanelStockRoute
  AdminPanelTodoRoute: typeof AdminPanelTodoRoute
  AdminPanelIndexRoute: typeof AdminPanelIndexRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelCalidadRoute: AdminPanelCalidadRoute,
  AdminPanelClientesRoute: AdminPanelClientesRoute,
  AdminPanelConfiguracionRoute: AdminPanelConfiguracionRoute,
  AdminPanelEmpaquetadoRoute: AdminPanelEmpaquetadoRoute,
  AdminPanelEmpleadosRoute: AdminPanelEmpleadosRoute,
  AdminPanelEnviosRoute: AdminPanelEnviosRoute,
  AdminPanelGruposRoute: AdminPanelGruposRoute,
  AdminPanelPagosRoute: AdminPanelPagosRoute,
  AdminPanelPedidosRoute: AdminPanelPedidosRoute,
  AdminPanelPersonalizadosRoute: AdminPanelPersonalizadosRoute,
  AdminPanelProduccionRoute: AdminPanelProduccionRoute,
  AdminPanelProductosRoute: AdminPanelProductosRoute,
  AdminPanelReclamosRoute: AdminPanelReclamosRoute,
  AdminPanelStockRoute: AdminPanelStockRoute,
  AdminPanelTodoRoute: AdminPanelTodoRoute,
  AdminPanelIndexRoute: AdminPanelIndexRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

interface CategoriasRouteChildren {
  CategoriasIdRoute: typeof CategoriasIdRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasIdRoute: CategoriasIdRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ProductsSlugRouteChildren {
  ProductsSlugDesignRoute: typeof ProductsSlugDesignRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugDesignRoute: ProductsSlugDesignRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  GruposRoute: GruposRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RegistrarMarcaRoute: RegistrarMarcaRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GroupSlugRoute: GroupSlugRoute,
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
