/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistrarMarcaRouteImport } from './routes/registrar-marca'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as GroupSlugRouteImport } from './routes/group.$slug'
import { Route as CategoriasIdRouteImport } from './routes/categorias.$id'
import { Route as AdminMachineRouteImport } from './routes/admin.machine'
import { Route as ProductsSlugDesignRouteImport } from './routes/products.$slug.design'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarMarcaRoute = RegistrarMarcaRouteImport.update({
  id: '/registrar-marca',
  path: '/registrar-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSlugRoute = GroupSlugRouteImport.update({
  id: '/group/$slug',
  path: '/group/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIdRoute = CategoriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriasRoute,
} as any)
const AdminMachineRoute = AdminMachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugDesignRoute = ProductsSlugDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ProductsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/grupos': typeof GruposRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/registrar-marca': typeof RegistrarMarcaRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/machine': typeof AdminMachineRoute
  '/categorias/$id': typeof CategoriasIdRoute
  '/group/$slug': typeof GroupSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/products/$slug/design': typeof ProductsSlugDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/products/$slug/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/products/$slug/design'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categorias'
    | '/customize'
    | '/grupos'
    | '/orders'
    | '/profile'
    | '/registrar-marca'
    | '/search'
    | '/sitemap.xml'
    | '/admin/machine'
    | '/categorias/$id'
    | '/group/$slug'
    | '/products/$slug'
    | '/products/$slug/design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  GruposRoute: typeof GruposRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RegistrarMarcaRoute: typeof RegistrarMarcaRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GroupSlugRoute: typeof GroupSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar-marca': {
      id: '/registrar-marca'
      path: '/registrar-marca'
      fullPath: '/registrar-marca'
      preLoaderRoute: typeof RegistrarMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$slug': {
      id: '/group/$slug'
      path: '/group/$slug'
      fullPath: '/group/$slug'
      preLoaderRoute: typeof GroupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$id': {
      id: '/categorias/$id'
      path: '/$id'
      fullPath: '/categorias/$id'
      preLoaderRoute: typeof CategoriasIdRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/admin/machine': {
      id: '/admin/machine'
      path: '/machine'
      fullPath: '/admin/machine'
      preLoaderRoute: typeof AdminMachineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug/design': {
      id: '/products/$slug/design'
      path: '/design'
      fullPath: '/products/$slug/design'
      preLoaderRoute: typeof ProductsSlugDesignRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMachineRoute: typeof AdminMachineRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMachineRoute: AdminMachineRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategoriasRouteChildren {
  CategoriasIdRoute: typeof CategoriasIdRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasIdRoute: CategoriasIdRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ProductsSlugRouteChildren {
  ProductsSlugDesignRoute: typeof ProductsSlugDesignRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugDesignRoute: ProductsSlugDesignRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  GruposRoute: GruposRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RegistrarMarcaRoute: RegistrarMarcaRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GroupSlugRoute: GroupSlugRoute,
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
